---
name: Flattened Terraform Workflow Checks - Pull Request

on:
  workflow_call:
    inputs:
      repository:
        description: 'Repository containing Terraform projects'
        type: string
        default: ''
      ref:
        description: 'Branch or ref to check out. Defaults to the PR head branch.'
        type: string
        default: ''
    secrets:
      VAULT_TOKEN:
        description: 'Vault token for accessing secrets'
        required: true

jobs:
  check_for_changes:
    name: Check for changed files
    uses: ./.github/workflows/_check_for_changes.yaml
    with:
      repository: ${{ inputs.repository }}
      ref: ${{ inputs.ref }}

  init_plan:
    name: Init and Plan Terraform Projects
    needs: check_for_changes
    if: |
      needs.check_for_changes.outputs.any_changed == 'true' &&
      contains(needs.check_for_changes.outputs.all_changed_files, '.tfvars')
    permissions:
      contents: 'read'
      id-token: 'write'
    uses: ./.github/workflows/_terraform-init-plan.yaml
    with:
      all_changed_dirs: ${{ needs.check_for_changes.outputs.all_changed_dirs }}
      # all_changed_files: ${{ needs.check_for_changes.outputs.all_changed_files }}
    secrets:
      VAULT_TOKEN: ${{ secrets.VAULT_TOKEN }}

  # apply_stg:
  #   name: Apply Terraform Projects to Staging Environment
  #   needs: init_plan
  #   if: |
  #     needs.check_for_changes.outputs.any_changed == 'true' &&
  #     contains(needs.check_for_changes.outputs.all_changed_files, '.tfvars') &&
  #     contains(needs.init_plan.outputs.tf_dirs, 'stg')
  #   permissions:
  #     contents: 'read'
  #     id-token: 'write'
  #   uses: ./.github/workflows/_terraform-apply.yaml
  #   with:
  #     tf_dirs: ${{ needs.init_plan.outputs.tf_dirs }}
  #     artifact_id: ${{ github.run_id }}
  #     environment: 'staging'
  #   secrets:
  #     VAULT_TOKEN: ${{ secrets.VAULT_TOKEN }}
