---
name: Flattened Terraform Release Workflow

on:
  workflow_call:
    inputs:
      repository:
        description: 'Repository containing Terraform projects'
        type: string
        default: ''
      ref:
        description: 'Branch or ref to check out. Defaults to the PR head branch.'
        type: string
        default: ''
      run-id:
        description: 'Run ID'
        type: string
        required: true
      environment:
        description: 'Environment to apply Terraform changes to'
        type: string
        required: true
    secrets:
      VAULT_TOKEN:
        description: 'Vault token for accessing secrets'
        required: true

jobs:
  check_for_changes:
    name: Check for changed files
    uses: ./.github/workflows/_check_for_changes.yaml
    with:
      repository: ${{ inputs.repository }}
      ref: ${{ inputs.ref }}

  init_apply:
    needs: check_for_changes
    if: |
      needs.check_for_changes.outputs.any_changed == 'true' &&
      contains(needs.check_for_changes.outputs.all_changed_files, '.tfvars')
    name: Init and Apply Terraform Projects
    permissions:
      contents: 'read'
      id-token: 'write'
      actions: 'read'
    uses: ./.github/workflows/_terraform-apply.yaml
    with:
      all_changed_dirs: ${{ needs.check_for_changes.outputs.all_changed_dirs }}
      run-id: ${{ inputs.run-id }}
      environment: ${{ inputs.environment }}
    secrets:
      VAULT_TOKEN: ${{ secrets.VAULT_TOKEN }}
