---
name: Flattened Terraform Workflow Checks - Pull Request

on:
  workflow_call:
    inputs:
      repository:
        description: 'Repository containing Terraform projects'
        type: string
        default: ''
      ref:
        description: 'Branch or ref to check out. Defaults to the PR head branch.'
        type: string
        default: ''
    secrets:
      VAULT_TOKEN:
        description: 'Vault token for accessing secrets'
        required: true
      TERRAFORM_GITHUB_PAT:
        description: 'GitHub Personal Access Token for Terraform Cloud'
        required: true

jobs:
  check_for_changes:
    name: Check for changed files
    uses: ./.github/workflows/_check_for_changes.yaml
    with:
      repository: ${{ inputs.repository }}
      ref: ${{ inputs.ref }}

  init_plan:
    needs: check_for_changes
    if: |
      needs.check_for_changes.outputs.any_changed == 'true' &&
      contains(needs.check_for_changes.outputs.all_changed_files, '.tfvars')
    name: Init and Plan Terraform Projects
    uses: ./.github/workflows/_terraform-init-plan.yaml
    with:
      # all_changed_dirs: ${{ needs.check_for_changes.outputs.all_changed_dirs }}
      all_changed_files: ${{ needs.check_for_changes.outputs.all_changed_files }}
    secrets:
      VAULT_TOKEN: ${{ secrets.VAULT_TOKEN }}
