---
name: Flattened Terraform Release Workflow

on:
  workflow_call:
    inputs:
      repository:
        description: 'Repository containing Terraform projects'
        type: string
        default: ''
      ref:
        description: 'Branch or ref to check out. Defaults to the PR head branch.'
        type: string
        default: ''
      skip_build:
        description: 'Skip the Packer build step. Defaults to false.'
        type: boolean
        default: false
    secrets:
      VAULT_TOKEN:
        description: 'Vault token for accessing secrets'
        required: true

jobs:
  check_for_changes:
    name: Check for changed files
    uses: ./.github/workflows/_check_for_changes.yaml
    with:
      repository: ${{ inputs.repository }}
      ref: ${{ inputs.ref }}

  apply:
    needs: check_for_changes
    if: |
      needs.check_for_changes.outputs.any_changed == 'true' &&
      contains(needs.check_for_changes.outputs.all_changed_files, '.tf') &&
      inputs.skip_build != 'true'
    name: Init and Apply Terraform Projects
    uses: ./.github/workflows/_terraform-apply.yaml
    with:
      all_changed_dirs: ${{ needs.check_for_changes.outputs.all_changed_dirs }}
    secrets:
      VAULT_TOKEN: ${{ secrets.VAULT_TOKEN }}

