---
name: Packer Validate and Init Stage

on:
  workflow_call:
    inputs:
      repository:
        description: 'Repository containing Packer templates'
        type: string
        default: ''
      ref:
        description: 'Branch or ref to check out'
        type: string
        default: ''
      all_changed_dirs:
        description: 'List of unique directory names containing changed files'
        type: string
        default: ''
    secrets:
      VAULT_TOKEN:
        description: 'Vault token for accessing secrets'
        required: true

jobs:
  validate_init:
    name: Validate and Init Packer Templates
    runs-on: arc-runners
    steps:
      - name: Checkout Code
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10
        with:
          repository: ${{ inputs.repository || github.repository }}
          ref: ${{ inputs.ref || github.head_ref }}

      - name: Setup Packer
        uses: hashicorp/setup-packer@ce93c3c08a6c2ff2275bf4b54ff0d9a75f6c9789

      - name: Format Validate and Init Packer
        env:
          ALL_CHANGED_DIRS: ${{ inputs.all_changed_dirs }}
          VAULT_ADDR: ${{ vars.VAULT_ADDR }}
          VAULT_TOKEN: ${{ secrets.VAULT_TOKEN }}
        run: |
          for dir in $ALL_CHANGED_DIRS; do
            echo "::notice::=== Processing $dir ==="
            echo "::notice::Running packer fmt -check for $dir"
            packer fmt -check "$dir"
            echo "::notice::Running packer init for $dir"
            packer init "$dir"
            echo "::notice::Running packer validate for $dir"
            packer validate "$dir"
            echo "::notice::Finished validating and initializing $dir"
          done
