---
name: Retrieve Vault Secret

on:
  workflow_call:
    inputs:
      secret_path:
        description: 'Path of the secret to retrieve'
        required: false
        type: string

permissions:
  contents: read
  id-token: write

jobs:
  retrieve_secret:
    runs-on: arc-runners
    steps:
      - name: Retrieve secret from Vault
        uses: hashicorp/vault-action@892a26828f195e65540a40b4768ae4571f51ebfc
        with:
          url: ${{ secrets.VAULT_ADDR }}
          method: jwt
          role: gha-vsphere-stg
          path: jwt
          secrets: |
            "{{ inputs.secret_path }}" | VSPHERE_USER

