---
name: Retrieve Vault Secret

on:
  workflow_dispatch:
    inputs:
      secret_name:
        description: 'Name of the secret to retrieve'
        required: true
        type: string
  pull_request:

jobs:
  retrieve_secret:
    runs-on: arc-runners
    steps:
      - name: Retrieve secret from Vault
        uses: hashicorp/vault-action@892a26828f195e65540a40b4768ae4571f51ebfc
        with:
          url: ${{ secrets.VAULT_ADDR }}
          method: jwt
          role: gha-vsphere-prod
          path: jwt
          secrets: |
            secret/vsphere/prod terraform_username | VSPHERE_USER

      - name: Debug secret
        run: |
          echo "VSPHERE_USER=${{ env.VSPHERE_USER }}"
