---
name: Init and Plan Terraform
on:
  workflow_call:
    inputs:
      repository:
        description: 'Repository containing Terraform code to lint'
        type: string
        default: ''
      ref:
        description: 'Branch or ref to check out. Defaults to the PR head branch.'
        type: string
        default: ''
      all_changed_dirs:
        description: 'List of all changed dirs'
        type: string
        default: ''
      auth_token:
        description: 'Google Cloud auth token'
        type: string
        default: ''
      project_id:
        description: 'Google Cloud project ID'
        type: string
        default: ''
    secrets:
      VAULT_TOKEN:
        description: 'Vault token for accessing secrets'
        required: true

jobs:
  set_files_dirs:
    name: Set Changed Files and Directories
    permissions:
      contents: 'read'
    runs-on: arc-runners
    outputs:
      tf_dirs: ${{ steps.get-changed-dirs.outputs.tf_dirs }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10
        with:
          repository: ${{ inputs.repository || github.repository }}
          ref: ${{ inputs.ref || github.head_ref }}

      - name: Get dirs of changed Terraform files
        id: get-changed-dirs
        env:
          ALL_CHANGED_DIRS: ${{ inputs.all_changed_dirs }}
        run: |
          for dir in $ALL_CHANGED_DIRS; do
            if find $dir -maxdepth 1 -type f -name "*.tfvars" | grep -q tfvars; then
              tf_dirs+=("${dir}")
            fi
          done
          echo "Terraform Dirs - ${tf_dirs[*]}"
          json_array=$(jq --compact-output --null-input '$ARGS.positional' --args "${tf_dirs[@]}")
          echo "tf_dirs=${json_array}" >> "$GITHUB_OUTPUT"

  init_plan:
    name: Init and Plan Terraform Project
    needs: set_files_dirs
    permissions:
      contents: 'read'
      id-token: 'write'
      pull-requests: 'write'
    runs-on: arc-runners
    strategy:
      matrix:
        tf_dir: ${{ fromJSON(needs.set_files_dirs.outputs.tf_dirs) }}
    env:
      VAULT_ADDR: ${{ vars.VAULT_ADDR }}
      VAULT_TOKEN: ${{ secrets.VAULT_TOKEN }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10
        with:
          repository: ${{ inputs.repository || github.repository }}
          ref: ${{ inputs.ref || github.head_ref }}

      - name: Run terraform init
        working-directory: ${{ matrix.tf_dir }}
        env:
          DIR: ${{ matrix.tf_dir }}
        run: |
          echo "Running terraform init for $DIR"
          terraform init -backend-config="prefix="${DIR}")" -input=false

      - name: Run terraform validate
        working-directory: ${{ matrix.tf_dir }}
        env:
          DIR: ${{ matrix.tf_dir }}
        run: |
            echo "Running terraform validate for $DIR"
            terraform validate

      - name: Run terraform plan
        id: plan
        working-directory: ${{ matrix.tf_dir }}
        env:
          DIR: ${{ matrix.tf_dir }}
        run: |
          echo "Running terraform plan for $DIR"
          terraform plan -input=false -out tfplan

      - name: Post terraform plan to PR
        uses: actions/github-script@v7
        with:
          script: |
            const output = `#### Terraform Plan: \`${{ steps.plan.outcome }}\`
            <details><summary>Show Plan</summary>\n\`\`\`\n${{ steps.plan.outputs.stdout }}\n\`\`\`\n</details>`;
            github.rest.issues.createComment({ ...context.issue, body: output });
