---
name: Init and Plan Terraform
on:
  workflow_call:
    inputs:
      repository:
        description: 'Repository containing Terraform code to lint'
        type: string
        default: ''
      ref:
        description: 'Branch or ref to check out. Defaults to the PR head branch.'
        type: string
        default: ''
      all_changed_dirs:
        description: 'List of all changed dirs'
        type: string
        default: ''
      auth_token:
        description: 'Google Cloud auth token'
        type: string
        default: ''
      project_id:
        description: 'Google Cloud project ID'
        type: string
        default: ''
    secrets:
      VAULT_TOKEN:
        description: 'Vault token for accessing secrets'
        required: true

jobs:
  set_files_dirs:
    name: Set Changed Files and Directories
    permissions:
      contents: 'read'
    runs-on: arc-runners
    outputs:
      tf_dirs: ${{ steps.get-changed-dirs.outputs.tf_dirs }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10
        with:
          repository: ${{ inputs.repository || github.repository }}
          ref: ${{ inputs.ref || github.head_ref }}

      - name: Get dirs of changed Terraform files
        id: get-changed-dirs
        env:
          ALL_CHANGED_DIRS: ${{ inputs.all_changed_dirs }}
        run: |
          for dir in $ALL_CHANGED_DIRS; do
            if find $dir -maxdepth 1 -type f -name "*.tf*" then
              tf_dirs+=("${dir}")
            fi
          done
          echo "tf_dirs=${tf_dirs[*]}" >> "$GITHUB_OUTPUT"

  init_plan:
    name: Init and Plan Terraform Project
    needs: set_files_dirs
    permissions:
      contents: 'read'
      id-token: 'write'
      pull-requests: 'write'
    runs-on: arc-runners
    strategy:
      matrix:
        tf_dir: ${{ fromJSON(needs.set_files_dirs.outputs.tf_dirs) }}
    env:
      VAULT_ADDR: ${{ vars.VAULT_ADDR }}
      VAULT_TOKEN: ${{ secrets.VAULT_TOKEN }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10
        with:
          repository: ${{ inputs.repository || github.repository }}
          ref: ${{ inputs.ref || github.head_ref }}

      - name: Run terraform init
        id: init
        working-directory: ${{ matrix.tf_dir }}
        env:
          DIR: ${{ matrix.tf_dir }}
        run: |
          echo "Running terraform init for $DIR"
          terraform init -backend-config="prefix="${DIR}")" -input=false

      - name: Post Init
        if: always() && github.ref != 'refs/heads/main' && (steps.init.outcome == 'success' || steps.init.outcome == 'failure')
        uses: robburger/terraform-pr-commenter@72c6e45eced6641488a6cf3ff104b7b9bda9c66c
        with:
          commenter_type: init
          commenter_input: ${{ format('{0}{1}', steps.init.outputs.stdout, steps.init.outputs.stderr) }}
          commenter_exitcode: ${{ steps.init.outputs.exitcode }}

      - name: Run terraform validate
        id: validate
        working-directory: ${{ matrix.tf_dir }}
        env:
          DIR: ${{ matrix.tf_dir }}
        run: |
            echo "Running terraform validate for $DIR"
            terraform validate

      - name: Post Validate
        if: always() && github.ref != 'refs/heads/main' && (steps.validate.outcome == 'success' || steps.validate.outcome == 'failure')
        uses: robburger/terraform-pr-commenter@72c6e45eced6641488a6cf3ff104b7b9bda9c66c
        with:
          commenter_type: validate
          commenter_input: ${{ format('{0}{1}', steps.validate.outputs.stdout, steps.validate.outputs.stderr) }}
          commenter_exitcode: ${{ steps.validate.outputs.exitcode }}

      - name: Run terraform plan
        id: plan
        working-directory: ${{ matrix.tf_dir }}
        env:
          DIR: ${{ matrix.tf_dir }}
        run: |
          echo "Running terraform plan for $DIR"
          terraform plan -input=false -out tfplan

      - name: Post Plan
        if: always() && github.ref != 'refs/heads/main' && (steps.plan.outcome == 'success' || steps.plan.outcome == 'failure')
        uses: robburger/terraform-pr-commenter@72c6e45eced6641488a6cf3ff104b7b9bda9c66c
        with:
          commenter_type: plan
          commenter_input: ${{ format('{0}{1}', steps.plan.outputs.stdout, steps.plan.outputs.stderr) }}
          commenter_exitcode: ${{ steps.plan.outputs.exitcode }}