---
name: Feature Branch Workflow / GitHub Actions

on:
  push:
    branches-ignore:
      - main

permissions:
  contents: read

jobs:
  gha-checks:
    name: GitHub Actions Feature Branch Workflow Checks
    uses: ./.github/workflows/_flattened-gha-f-workflow-checks.yaml
    with:
      repository: ${{ github.repository }}
      ref: ${{ github.head_ref || github.ref_name }}
      yamllint_config: .yamllint.yaml
